name: shopping_demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  badges: ^3.0.2
  share_plus: ^6.3.1
  get: 4.6.5
  flutter_form_builder: ^7.8.0
  smooth_page_indicator:
  fluttertoast: ^8.0.9
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/json/
    - assets/images/

  fonts:
    - family: popBold
      fonts:
        - asset: fonts/pop.ttf

